#pragma once

// NOTE(dkorolev): This is what pure C autogenerated struct should be, so that it is binary-compatible.

#include "typesystem/reflection/typeid.h"

struct ShallowCurrentStruct {
  virtual ~ShallowCurrentStruct() = default;
};

struct Number final : ShallowCurrentStruct {
  uint32_t value;
};

CURRENT_INJECT_TYPE_ID(Number, 0x7fbe52ead300e3ae);
